# Generated by Django 2.0.1 on 2020-05-08 09:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vk_group', models.IntegerField()),
                ('name_group', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vk_post', models.IntegerField()),
                ('name_post', models.CharField(max_length=1000)),
                ('body_post', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idvk', models.IntegerField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('bd', models.DateField(verbose_name=datetime.date)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='id_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.UserAuthor'),
        ),
        migrations.AddField(
            model_name='groups',
            name='id_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.UserAuthor'),
        ),
    ]
